#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("preguntaods.Resource", IsApplication=true)]

namespace preguntaods
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorSecundary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int camposInf = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int pre = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int preAcierto = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int preFallo = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int userNotLog = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int atras = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int button1 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int button2 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int button3 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int button4 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int buttonAvatar = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int contraseña = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int contraseña2 = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int correo = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int ererere = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int error = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int inicioSesion = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int linearLayout1 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int linearLayoutMain = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int linearLayoutRecuperarPass = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int nombreUsuario = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int partidaB = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int perfil = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int pregunta = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int registrar = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int registroB = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int textHasOlvidado = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int textView1 = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int textView2 = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int textView3 = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int textView4 = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int textViewPass = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int textViewUserName = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int timeBar = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int volver = 2130903069;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int inicioSesion = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int menu = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int pregunta = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int registro = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_adaptive_back = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_adaptive_fore = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_launcher_foreground = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ic_launcher_round = 2131034116;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int megaman_acierto = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int megaman_error = 2131099649;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int underline = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int HiddenTitleTheme = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int invisible_action_bar_style = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
